CREATE TABLE Costs
(
Costs_CostsID INT IDENTITY(1,1) NOT NULL,
Costs_CaseID INT NOT NULL,
Costs_DateAssCosts SMALLDATETIME NULL,
Costs_CostsFE VARCHAR(50) NULL,
Costs_CostsTL VARCHAR(50) NULL,
Costs_CostsTA VARCHAR(50) NULL,
Costs_DateAuthAss SMALLDATETIME NULL,
Costs_ExtDraftsPerson BIT NULL,
Costs_CostsWorkType	VARCHAR (10) Null,
Costs_Party	VARCHAR (10) Null,
Costs_CostsGoalHrs	INT NULL,
Costs_CostsTimeSpent	INT NULL,
Costs_PCSCostsClaimed	MONEY NULL,
Costs_PCSDisbClaimed	MONEY NULL,
Costs_PTPATEClmd	MONEY NULL,
Costs_PSuccessFeeClmd	MONEY NULL,
Costs_PSuccessPercentClmd INT NULL,
Costs_PTotalCSCostsClaimed,MONEY NULL,
Costs_PHourlyRateClaimed,MONEY NULL,
Costs_PCSHoursClaimed	INT NULL,
Costs_PCSCostsPaid	MONEY NULL,
Costs_PCSDisbPaid	MONEY NULL,
Costs_PATEPremiumPaid	MONEY NULL,
Costs_PSuccessFeePaid	MONEY NULL,
Costs_PSuccessPercentPaid INT NULL, 
Costs_PTotalCSCostsPaid	MONEY NULL,
Costs_PCSHourlyRatePaid	MONEY NULL,
Costs_PCSHoursPaid	INT NULL, 
Costs_PCostsMINotes	VARCHAR (255) NULL,
Costs_RCSCostsClaimed	MONEY NULL,
Costs_RCSDisbClaimed	MONEY NULL,
Costs_RTPATEClmd	MONEY NULL,
Costs_RSuccessFeeClmd	MONEY NULL,
Costs_RSuccessPercentClmd INT NULL,
Costs_RTotalCSCostsClaimed MONEY NULL,
Costs_RHourlyRateClaimed MONEY NULL,
Costs_RCSHoursClaimed	INT NULL,
Costs_RCSCostsRCVD	MONEY NULL,
Costs_RCSDisbRCVD	MONEY NULL,
Costs_RATEPremiumRCVD	MONEY NULL,
Costs_RSuccessFeeRCVD	MONEY NULL,
Costs_RSuccessPercentRCVD INT NULL,
Costs_RTotalCSCostsRCVD	MONEY NULL,
Costs_RCSHourlyRateRCVD	MONEY NULL,
Costs_RCSHoursRCVD	INT NULL,
Costs_RCostsMINotes	VARCHAR (255) NULL,
Costs_GlobSett	Bit NULL,
Costs_PredCosts	Bit NULL,
Costs_AuditNetVAT MONEY NULL,
Costs_AuditVAT	MONEY NULL,
Costs_DisbNetVAT MONEY NULL,
Costs_DisbVAT	MONEY NULL,
Costs_AudiitIncVAT MONEY NULL
Costs_CreatUser VARCHAR(50) NOT NULL,
Costs_CreateDate SMALLDATETIME NOT NULL
)
