--SMJ - Changed to include new LV fields

/****** Object:  View [dbo].[_HBM_MATTER_USR_DATA]    Script Date: 05/24/2012 15:27:28 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[_HBM_MATTER_USR_DATA]'))
DROP VIEW [dbo].[_HBM_MATTER_USR_DATA]
GO

/****** Object:  View [dbo].[_HBM_MATTER_USR_DATA]    Script Date: 05/24/2012 15:27:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[_HBM_MATTER_USR_DATA]
AS
SELECT     NORWELL_CLIENT_NO, NORWELL_MATTER_NO, INS_COMPANY_CONTACT, DEPARTMENT_TEAM, INS_COMPANY_REF, BROKER_REF, L_C_O_REF, SOLINV, 
                      TRANSFER_TO_FLOCASE, DATE_TRNSFD_TO_FLOCASE, RESERVED_FOR_NEWCASE, CAPITA_FSCS, DTI_INVOLVEMENT, IICL_TYPE_OF_CASE, 
                      IICL_INSURED_STATUS, CAPITA_CLAIM_TYPE, FSCS_PROTECTED, INSURED_CONTACT, INSURED_REF, PH_FIRST_ADDRESS, PH_POSTCODE, 
                      INSURED_OCCUPATION, POLICY_TYPE, INSURED_VAT_REGISTERED, INSURED_GROUP, INSURED_SUB_GROUP, INSURED_POLICYHOLDER, POLICY_NO, 
                      DATE_CLIENT_NOTIFIED, DATE_OF_LET_OF_CLAIM, CLIENT_TYPE, CONDITIONAL_FEE, CLAIM_TYPE, CLIENT_CONTACT, CLIENT_LEGAL_AID, CLIENT_REF, 
                      CLIENT_VAT_REGISTERED, REFERRED_BY, CLIENT_OCCUPATION, STAGE_OF_CLAIM, DATE_OF_PROCEEDINGS, DATE_OF_SETTLEMENT, VALUE_OF_CLAIM, 
                      COURT_TRACK, DATE_INSTRUCTED, DATE_ACCIDENT_INCIDENT, PLACE_OF_ACCIDENT, OBSOLETE_1, OBSOLETE_2, DESCRIPTION_OF_INJURY, SEVERITY, 
                      SYMPTOMS, ONSET_SYMPTOMS_DATE, TP_INSURER, TP_NAME, TP_ADDRESS, TP_POSTCODE, PLAINT_DECD_SEX, P_D_DATE_OF_BIRTH, OBSOLETE_3, 
                      COURT_LOCATION, COURT_CASE_NO, PARTIAL_VAT_EXEMPT, PREMATURE_ISSUE, PURCHASE_ORDER_NO, OPENING_RESERVE, TRIAL_DATE, 
                      CLAIMANT_FIRST_NAME, CLAIMANT_SURNAME, CLAIMANT_DOB, CLAIMANT_SOL_REF, CLAIMANT_SOL_FIRM, CLAIMANT_SOL_LOCATION, CB_TYPE_OF_CLAIM, 
                      CB_CLAIM_SETTLED, REASON_FOR_SETTLEMENT, DATE_REC_BY_COSTS, NAME_OF_COSTS_HANDLER, COST_CATEGORY, DATE_OF_COST_STLMNTM, 
                      FILE_OPENER_INITIALS, FILE_OPENER_NOTES, DCT_NOTES, INSURED_EXCESS, ADVICE_ONLY, REPAIRING_GARAGE, CREDIT_HIRE_ORG, CREDIT_HIRE_YN, 
                      LITIGATION_AVOIDABLE, LITIGATED, CASE_OUTCOME, TRAV_ATTRITIONAL_WORK, PREVIOUS_BLM_NO, Z_REF_REASON, AZ_MOJ_STATUS, 
                      AZ_MOJ_ESCAPE_REASON, CLIENT_INSTR_TYPE, CLIENT_LIT_REASON, RBSF_SETTLEMENT_METHOD, CLAIMS_OUTCOME_ADVSR, QBE_COURT_TRACK, 
                      MITSUI_SUBSIDIARY, MITSUI_DIVISION, QBE_MAX_INCURRED, QBE_INITIAL_INCURRED, HANDLER_EMAIL_ADDRESS, QBE_TYPE_OF_CLAIM, 
                      QBE_CLASS_OF_BUS, MITSUI_INSURED_NAME, QBE_REASON_FOR_LIT, QBE_DIVISION, AVIVA_LOC, AVIVA_BCHAN, AVIVA_LOSSA, NON_LIT_OR_LIT, 
                      OPS_OR_TCS, PREV_DEF_SOL_REF, PREV_DEF_SOL_HANDLER, PREV_DEF_SOL_FIRM, NUD_RSN_PRELIT_INSTR, URGENT_CLAIM, NUD_VALUE_BAND, 
                      NUD_RSN_FOR_NON_DEL, NUD_PRE_LIT_BLM_FILE, PROVISION_TYPE_1_4, PROVISION_PERCENT, FRAUD, FRAUD_TYPE, CONNEXIONS_REF, 
                      NUD_COURT_TRACK, NUD_DISEASE_TYPE, NUD_INS_COVER_PERIOD, NUD_DATE_INIT_EXPOS, FSG_REF, WARBURTONS_SUBSID, WARBURTONS_LOCATION, 
                      VEHICLE_REG, NOTIFICATION_DATE, DRIVER_NAME, DRIVER_DOB, VEHICLE_TYPE, COLLISION_CODE, CLAIMANTS_DOB, DELEGATED_AUTHORITY, 
                      LTSB_LOSS_CODE, LTSB_BUSINESS_UNIT, NUMBER_OF_CLAIMANT, NU_FRAUD_TYPE, SCAM_CLAIM, SCAM_PROJECT_NAME, SIMS_LIT_CODES, 
                      JUBILEE_LIT_CODES, RBSF_INSTR_TYPE, RBSF_LIT_REASON, RBSI_ORIG_OFFICE, RBSI_BRAND, INDEMNITY, RBS_TEAM, LV_TPE_OF_FRAUD, 
                      MIB_HANDLER_CODE, MIB_CLAIM_AREA, FIRST_CLAIMANT_NAME, SECOND_CLAIMANT_NAME, THIRD_CLAIMANT_NAME, FOURTH_CLAIMANT_NAME, 
                      FIFTH_CLAIMANT_NAME, SIXTH_CLAIMANT_NAME, SEVENTH_CLAIMANT_NAME, EIGHTH_CLAIMANT_NAME, MIB_TYPE_OF_INJURY, MIB_PROFILE_OF_WK_1, 
                      MIB_PROFILE_OF_WK_2, NINTH_CLAIMANT_NAME, TENTH_CLAIMANT_NAME, ALLIANZ_CATEGORY, TRANSFER_TO_HB, DATE_TRANSFERRED_TO_HB, 
                      AUDIT_DATE, COMMISSION, Z_OFFSHORE_PAY_SCOPE, ALLIANCE_C_ROOT_CAUSE, ALLIANZ_C_TYPE, ALLIANZ_C_VALUE_BAND, ACE_DATE_INSTRUCTED, 
                      ACE_ADVOCATOR, ACE_COURT_TRACK, ACE_CLASS_OF_BUSINESS, ACE_DATE_LIT_COMM, ACE_TYPE_OF_INSTRUCTION, ACE_PHASE_OF_INSTRUC, 
                      ACE_TOTAL_INDEMNITY, ACE_PERCENT_LIABILITY, ACE_NAME_OF_INSURED, ACE_REASON_FOR_LIT, AZ_MAJOR_LOSS_CASE, FORTIS_TEAM, 
                      FORTIS_INSTR_REASON, FORTIS_TRACK, FORTIS_VALUE_BAND, JUBILEE_LIT_CODE2, ALLIANZ_C_VAL_BAND_2, LINKED_BLM_CASE, TIME_SUMMARY_TYPE, 
                      CLIENT_CHARGE_TYPE, CLIENT_BILLING_REF, AUTO_BILL_EXCLUDED, BILLING_FREQUENCY, USE_BILLING_ADDRESS, AUTO_TIME_BILL_DETS, 
                      VAT_BILLING_CATEGORY, VAT_ADDRESS_CODE, FIXED_FEES, ZURICH_ID, ZURICH_REF_CODE, ZURICH_CLAIM_NO, ZURICH_DEL_AUTHORITY, 
                      ZURICH_ACRONYM, BRANCH_OF_ZURICH, Z_COURT_TRACK_CODE, Z_CLASS_OF_BUSINESS, Z_INCIDENT_DATE, Z_DATE_INSTRUCTED, 
                      Z_LITIGATION_COMMENCED, Z_INJURY_CLAIM, Z_NATURE_OF_INJURY, Z_LIABILITY_ADMITTED, Z_ADMITTED_DATE, Z_QUANTUM_CONCLUDED, 
                      Z_CLAIMANT_COSTS, MATTER_CODE, ADVANCED_FEES, LAST_MODIFIED, INACTIVE, SECURITY_ID, MATTER_UNO, GENERAL_DAMAGES, FULL_LIABILITY, 
                      COA_FIGURE, QBE_LIABILITY_PERCENT, FINAL_FEE_PAYABLE, RBS_NOTIFIED_RESERVE, CLIENT_NOT_RESERVE, Z_INITIAL_CASE_VALUE, 
                      Z_AGREED_DAMAGES, BRIT_CLAIMANT_TYPE, BRIT_CLAIMANT_OCCUPATION, BRIT_NATURE_OF_INJURY, BRIT_CLAIM_CATEGORY, BRIT_DATE_NOM_REC, 
                      BRIT_TYPE_OF_CASE, BRIT_COURT_TRACK, BRIT_REAS_FOR_INSTRUC, BRIT_REASON_LIT_AVOIDABLE, NFU_INJURY, NFU_COURT_TRACK, ECC_COURT_TRACK, 
                      MITSUI_ACC_DETAILS, HRG_BRANCH, HRG_ADDRESS, HRG_STORE, HRG_DISB_CENTRE, BRIEF_INJURY_DESCRIP, ACCIDENT_DETAILS, VEHICLE_DETAILS, 
                      MI_INCL, AVIVA_FR_TOT_FEE, AVIVA_FE_LEGAL_SPEND, FRAUD_REFERRAL_DATE, FRAUD_INVESTIGATION_DATE, FRAUD_CONCLUSION_DATE, 
                      FRAUD_CONCLUSION_TYPE, ACCIDENT_LOCATION, CLAIMANT_1_RESERVE, CLAIMANT_2_RESERVE, CLAIMANT_3_RESERVE, MOJ_3_CASE, MOJ_STAGE_CASE, 
                      OUTSOURCE_STAGE_CASE, OUTSOURCE_EXCESSIVE_INSTR, MI_EXCL_REASON, BROKERBILITY, AVIVA_ROOT_CAUSE, AVIVA_DISPUTE_REASON, 
                      ACE_PROCEDURAL_ONLY, LTSB_TYPE, EXIT_FROM_MOJ, AVIVA_MOJ_STATUS, LV_CAT_AT_INST, LV_NO_OF_CLAIMANTS, LV_PRODUCT, LV_CLAIM_OR_DEF, 
                      LV_TRACK, LV_WORK_TYPE, LV_TYPE, LV_PI_INVOLVED, LV_AVOID_LIT, LV_REASON_FOR_LIT
--DEV AND TEST                      
FROM         [MAN81SQL\MANZ01C03].ADERANTTRAINBLM.dbo._HBM_MATTER_USR_DATA AS _HBM_MATTER_USR_DATA_1
-- SCHOOL AND LIVE
--FROM         [MANZ01C03\MANZ01C03].ADERANTLIVEBLM.dbo._HBM_MATTER_USR_DATA AS _HBM_MATTER_USR_DATA_1
GO
