select 
c.CLIENT_NUMBER,
m.MATTER_NUMBER
FROM       [man81sql\manz01c03].[AderantTrainBLM].dbo.HBM_MATTER m INNER JOIN
dbo.HBM_CLIENT c ON m.CLIENT_UNO = c.CLIENT_UNO INNER JOIN
dbo._HBM_MATTER_USR_DATA u ON m.MATTER_UNO = u.MATTER_UNO 
where 
c.CLNT_CAT_CODE = 'ZUR'
and 
c.CLIENT_NUMBER = 136179
order by m.MATTER_NUMBER

select
c.CLIENT_NUMBER,
m.MATTER_NUMBER
FROM      AderantTrainBLM_REPL.dbo.HBM_MATTER m INNER JOIN
dbo.HBM_CLIENT c ON m.CLIENT_UNO = c.CLIENT_UNO INNER JOIN
dbo._HBM_MATTER_USR_DATA u ON m.MATTER_UNO = u.MATTER_UNO 
where 
c.CLNT_CAT_CODE = 'ZUR'
and 
c.CLIENT_NUMBER = 136179
order by m.MATTER_NUMBER