--SMJ - ADD MILookUps

INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','A1','Mesothelioma','Mesothelioma','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','A2','Pleural plaques','Pleural plaques','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','A3','Pleural thickening','Pleural thickening','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','A4','Asbestosis','Asbestosis','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','A5','Lung Cancer','Lung Cancer','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','A6','Asthma','Asthma','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','A7','Rhinitis','Rhinitis','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','A8','Silicosis','Silicosis','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','A9','Sick building syndrome','Sick building syndrome','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','B10','WRULD - factory','WRULD - factory','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','B11','WRULD - typing','WRULD - typing','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','B12','Back, cumulative','Back, cumulative','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','B13','Back, non cumulative','Back, non cumulative','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','B14','Fibromyalgia / chronic pain','Fibromyalgia / chronic pain','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','B15','Knee Cumulative','Knee Cumulative','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','C16','VWF / HAVS','VWF / HAVS','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','C17','CTS only','CTS only','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','C18','Whole body vibration','Whole body vibration','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','D19','NIHL','NIHL','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','D20','Tinnitus only','Tinnitus only','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','D21','Acoustic shock','Acoustic shock','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','E22','Work overload','Work overload','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','E23','Bullying / harassment','Bullying / harassment','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','E24','Work overload & bullying / harassment','Work overload & bullying / harassment','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','F25','Respiratory illness','Respiratory illness','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','F26','Exacerbation of respiratiry illness','Exacerbation of respiratiry illness','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','F27','Cardiovascular','Cardiovascular','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','F28','Cancer','Cancer','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','G29','Power lines','Power lines','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','G30','Mobile phones','Mobile phones','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','G31','Electrical applications','Electrical applications','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','H32','Anthrax','Anthrax','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','H33','Brucellosis','Brucellosis','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','H34','Leptospirosis (Weils disease)','Leptospirosis (Weils disease)','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','I35','Carbon monoxide','Carbon monoxide','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','I36','Deep Vein Thrombosis','Deep Vein Thrombosis','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','I37','Dermatitis','Dermatitis','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','I38','Food poisoning','Food poisoning','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','I39','Legionnaires disease','Legionnaires disease','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','I40','Other - please specify','Other - please specify','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'DISTYPE','I41','Toxic mold','Toxic mold','AV-D',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'REALITSUCC','BREACH','Breach','Breach','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REALITSUCC','CAUS','Causation','Causation','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REALITSUCC','LIMBREACH','Limitation, Breach','Limitation, Breach','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REALITSUCC','PROCOV','Procedural Cover','Procedural Cover','AV-D',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'CRTTRACK','PRE','Pre-Litigation','Pre-Litigation','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CRTTRACK','FAS','Fast Track','Fast Track','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CRTTRACK','MUL','Multi Track ','Multi Track ','AV-D',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'CSTRECDEF','REC','Recovery','Recovery','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CSTRECDEF','DEF','Defence','Defence','AV-D',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT','LIABDISP','Liability In Dispute','Liability In Dispute','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT','INEVTPLDLQ','Insufficient Evidence to Take Pre-Lit Decision on Liability or Quantum','Insufficient Evidence to Take Pre-Lit Decision on Liability or Quantum','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT','FAITPLDLQ','Failure to Take Pre-Lit Decision on Liability or Quantum','Failure to Take Pre-Lit Decision on Liability or Quantum','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT','HSEPROS','HSE Prosecution','HSE Prosecution','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT','QUADISP','Quantum in Dispute','Quantum in Dispute','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT','POLCOVDISP','Policy Cover Dispute','Policy Cover Dispute','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT','PRESETISS','Precedent Setting Issue','Precedent Setting Issue','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT','INQ','Inquest','Inquest','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT','LIMIT','Limitation','Limitation','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT','CSTCONDISP','Costs / Conduct Dispute','Costs / Conduct Dispute','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT','INFAPP','Infant Approval','Infant Approval','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT','RECACT','Recovery Action','Recovery Action','AV-D',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'REASTRIAL','LIABDISP','Libiability in Dispute','Libiability in Dispute','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASTRIAL','QUADISP','Quantum in Dispute','Quantum in Dispute','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASTRIAL','LIMIT','Limitation','Limitation','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASTRIAL','POLCOVDISP','Policy Cover Dispute','Policy Cover Dispute','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASTRIAL','CSTCONDISP','Costs / Conduct Dispute','Costs / Conduct Dispute','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASTRIAL','RECACT','Recovery Action','Recovery Action','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASTRIAL','PRESETISS','Precedent Setting Issue','Precedent Setting Issue','AV-D',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'REASLIT','NONLIT','Non litigated','Non litigated','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASLIT','CLAISOLCON','Claimant''s solicitor conduct','Claimant''s solicitor conduct','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASLIT','DELAVHND','Delay by Aviva case handler','Delay by Aviva case handler','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASLIT','LIMIT','Limitation','Limitation','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASLIT','DELMULTI','Delay due to multi parties','Delay due to multi parties','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASLIT','QUADISP','Quantum dispute','Quantum dispute','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASLIT','DELINS','Delay by insured','Delay by insured','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASLIT','VALIDDEN','Valid denial','Valid denial','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASLIT','UNRASSMAV','Unrealistic assessment by Aviva','Unrealistic assessment by Aviva','AV-D',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'AVDYESNO','Y','Yes','Yes','AV-D',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVDYESNO','N','No','No','AV-D',0, GETDATE(), 'SMJ'  
