--SMJ - ADD MILOOKUPS

INSERT INTO MILookupFieldDefinition SELECT 'TRIOUTCOME','DNGTT','Did not go to Trial','Did not go to Trial',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'TRIOUTCOME','WAT','Won at Trial','Won at Trial',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'TRIOUTCOME','LAT','Lost at Trial','Lost at Trial',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'AVVALBAND','V25K','£0 - £25k','£0 - £25k',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVVALBAND','V50K','£25k - £50k','£25k - £50k',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVVALBAND','V125K','£50k - £125k','£50k - £125k',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVVALBAND','V1M','£125k - £1million','£125k - £1million',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVVALBAND','V1MPLUS','£1million +','£1million +',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'CSTDLTNBLM','Y','Yes','Yes',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CSTDLTNBLM','N','No','No',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CSTDLTNBLM','NC','No Costs','No Costs',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'CRUAPPEAL','NA','N/A','N/A',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CRUAPPEAL','ONG','Ongoing','Ongoing',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CRUAPPEAL','SUCC','Successful','Successful',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CRUAPPEAL','UNSUCC','Unsuccesful','Unsuccesful',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'SETTSTATUS','PSDCSTDR','Passed to Cost Draughtsman','Passed to Cost Draughtsman',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'SETTSTATUS','HTNF','Handed to new firm','Handed to new firm',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'SETTSTATUS','SETTP36','Settled - Part 36 offer awarded','Settled - Part 36 offer awarded',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'SETTSTATUS','CWON','Case Won','Case Won',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'SETTSTATUS','CWTHD','Case withdrawn','Case withdrawn',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'SETTSTATUS','SETTCNA','Settled - costs not awarded','Settled - costs not awarded',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'SETTSTATUS','COMPCA','Completed - Costs Agreed','Completed - Costs Agreed',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'SETTSTATUS','NEWHAND','New handler','New handler',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'SETTSTATUS','LITIG','Litigated','Litigated',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'SETTSTATUS','SETTBEFTR','Settled before Trial','Settled before Trial',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'SETTSTATUS','LAT','Lost at Trial','Lost at Trial',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'SETTSTATUS','OTHREAS','Other - please give reason','Other - please give reason',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'REASUCC','LIASUCC','Liability Success','Liability Success',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASUCC','WAT','Win at Trial','Win at Trial',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASUCC','OFFNOTBT','Offer not beaten','Offer not beaten',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASUCC','OWNCSTREC','Own Costs Recovered','Own Costs Recovered',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASUCC','SUCCRUAPP','Successful CRU appeal','Successful CRU appeal',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASUCC','PCALITMAT','Predictive costs agreed on a litigated matter','Predictive costs agreed on a litigated matter',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASUCC','P36NTBT','Part 36 not Beaten','Part 36 not Beaten',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REASUCC','FRAUD','Fraud','Fraud',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'REAEXCOL','CRTAWA','Court Award','Court Award',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REAEXCOL','CASELAW','Case Law','Case Law',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REAEXCOL','FURTHMED','Further Medical','Further Medical',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REAEXCOL','JSBGDLN','JSB Guidelines','JSB Guidelines',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REAEXCOL','NOTEXC','Not Exceeded','Not Exceeded',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REAEXCOL','OTHFAC','Other Factors','Other Factors',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'REAEXCOL','NOCOL','No Colossus valuation supplied','No Colossus valuation supplied',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','BAS','Basildon','Basildon',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','BEL','Belfast','Belfast',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','BIR','Birmingham','Birmingham',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','BIS','Bishopbriggs','Bishopbriggs',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','BRA','Bradford','Bradford',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','BRI','Bristol','Bristol',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','CHE','Chelmsford','Chelmsford',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','CRO','Croydon','Croydon',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','DUN','Dundee','Dundee',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','EDI','Edinburgh','Edinburgh',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','EXE','Exeter','Exeter',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','GLA','Glasgow','Glasgow',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','INBAN','India - Bangalore','India - Bangalore',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','INNOI','India - Noida','India - Noida',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','INPUN','India - Pune','India - Pune',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','LEE','Leeds','Leeds',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','LIV','Liverpool','Liverpool',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','MAN','Manchester','Manchester',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','NEW','Newcastle','Newcastle',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','NOR','Norwich Commercial Centre','Norwich Commercial Centre',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','OTH','Other','Other',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','SIU','SIU','SIU',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','SOU','Southampton','Southampton',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','SEND','Southend','Southend',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','TCSLEG','TCS - Legal','TCS - Legal',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','TCSLIA','TCS - Liability','TCS - Liability',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','TCSMOT','TCS - Motor','TCS - Motor',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCLAILOC','WOR','Worthing','Worthing',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','BANG','Bangalore','Bangalore',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','BEACH','Beachcroft','Beachcroft',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','BLM','Berrymans Lace Mawer','Berrymans Lace Mawer',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','BIRM','Birmingham','Birmingham',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','CAP','Capita','Capita',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','CRAW','Crawfords','Crawfords',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','CIP','CIP','CIP',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','CUN','Cunningham Lindsey','Cunningham Lindsey',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','VLA','DLA','DLA',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','DWF','DWF','DWF',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','EXE','Exeter','Exeter',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','GLA','Glasgow','Glasgow',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','GRE','Greenwoods','Greenwoods',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','HF','Horwich Farrelly','Horwich Farrelly',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','HJ','Hugh James','Hugh James',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','KEO','Keoghs','Keoghs',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','MAN','Manchester','Manchester',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','NOI','Noida','Noida',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','NOR','Norwich','Norwich',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'INSTRUNIT','OTH','Other','Other',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'SERVINSTR','LIT','Litigated','Litigated',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'SERVINSTR','LITPO','Litigated post outsource','Litigated post outsource',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'SERVINSTR','OUTNC','Outsourced new claim','Outsourced new claim',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'SERVINSTR','OUTCL','Outsourced caseload','Outsourced caseload',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'SERVINSTR','OTH','Other','Other',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'AVCOMMOD','CP','Criminal Prosecutions','Criminal Prosecutions',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCOMMOD','FRAUD','Fraud','Fraud',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCOMMOD','FTDA','FT DA','FT DA',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCOMMOD','FTNDA','FT non DA','FT non DA',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCOMMOD','HSH','Household','Household',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCOMMOD','HSE','HSE','HSE',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCOMMOD','MTDA','MT DA','MT DA',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCOMMOD','MTNDA','MT non DA','MT non DA',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCOMMOD','PAD','PAD','PAD',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCOMMOD','INFAPP','Infant Approval','Infant Approval',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCOMMOD','CONSORD','Consent Order','Consent Order',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCOMMOD','OTH','Other','Other',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCOMMOD','INFONLY','Info only','Info only',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCOMMOD','ADVONLY','Advice Only','Advice Only',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'AVCATEGORY','MOTPROP','Motor-Property Only','Motor-Property Only',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCATEGORY','MOTINJ','Motor-Injury','Motor-Injury',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCATEGORY','ELINJ','EL-injury','EL-injury',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCATEGORY','PLINJ','PL-injury','PL-injury',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCATEGORY','ELENV','EL-Environmental','EL-Environmental',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCATEGORY','PLENV','PL-Environmental','PL-Environmental',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCATEGORY','PI','Professional Indemnity','Professional Indemnity',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCATEGORY','PLPROP','PL-Property','PL-Property',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCATEGORY','OTH','Other','Other',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVCATEGORY','CH','Credit Hire','Credit Hire',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','AMP','Amputation','Amputation',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','ARM','Arm Injury (not broken)','Arm Injury (not broken)',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','BACK','Back Injury','Back Injury',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','BLIND','Blindness/Injury to eyes','Blindness/Injury to eyes',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','BRINJCAT','Brain Injury-Catastrophic','Brain Injury-Catastrophic',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','BRINJOTH','Brain Injury-Other','Brain Injury-Other',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','BRK','Breaks/Fractures','Breaks/Fractures',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','BURN','Burns/Scarring','Burns/Scarring',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','DEAFD','Deafness/injury to ears','Deafness/injury to ears',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','CUTS','Cuts and Bruises','Cuts and Bruises',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','FATAL','Fatality','Fatality',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','INTINJ','Internal injuries','Internal injuries',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','LEGINJNB','Leg injury (not broken)','Leg injury (not broken)',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','NECKINJ','Neck Injury','Neck Injury',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','NONE','None','None',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','PSY','Psychological/Psychiatric','Psychological/Psychiatric',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','PARA','Paralysis','Paralysis',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVINJTYPE','SHOU','Shoulder Injury','Shoulder Injury',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'AVLITSTAT','NOTLIT','Not litigated','Not litigated',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVLITSTAT','LITIG','Litigated','Litigated',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVLITSTAT','P8ONLY','Part 8 only','Part 8 only',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVLITSTAT','LITPO','Litigated post outsource','Litigated post outsource',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVLITSTAT','PAD','PAD','PAD',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVLITSTAT','INFAPP','Infant Approval','Infant Approval',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'AVLITSTAT','CHONLY','Credit Hire only','Credit Hire only',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT1','LIAB','Liability','Liability',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT1','QUANT','Quantum','Quantum',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT1','LIABQUANT','Liability & Quantum','Liability & Quantum',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT1','LIMIT','Limitation','Limitation',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT1','NORESPAV','No response from Aviva','No response from Aviva',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT1','OTH','Other','Other',0, GETDATE(), 'SMJ'

INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT2','NOFFAV','No offer made by Aviva','No offer made by Aviva',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT2','OFFREJCLAI','Aviva offer rejected by claimant','Aviva offer rejected by claimant',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT2','OFFREJAV','Claimant offer rejected by Aviva','Claimant offer rejected by Aviva',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT2','NRCLAIOFF','No response to Claimant offer','No response to Claimant offer',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT2','NORESPAV','No response from Aviva','No response from Aviva',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT2','DISPFULL','Disputed in Full','Disputed in Full',0, GETDATE(), 'SMJ'
INSERT INTO MILookupFieldDefinition SELECT 'CAUSELIT2','OTH','Other','Other',0, GETDATE(), 'SMJ'
